### ISSUE TITLE
LocationSensor flushing happens on UI thread => forces error

### ISSUE THREAD

**Issue by paulgavrikov** [pscholl/cmotion#35]

**Comment by paulgavrikov** [comment]
03-25 08:50:02.726 12850-12850/es.uni_freiburg.de.cmotion W/System.err: java.lang.Throwable: stack dump
03-25 08:50:02.727 12850-12850/es.uni_freiburg.de.cmotion W/System.err:     at java.lang.Thread.dumpStack(Thread.java:490)
03-25 08:50:02.727 12850-12850/es.uni_freiburg.de.cmotion W/System.err:     at de.uni_freiburg.es.sensorrecordingtool.sensors.LocationSensor.onLocationChanged(LocationSensor.java:149)
03-25 08:50:02.728 12850-12850/es.uni_freiburg.de.cmotion W/System.err:     at de.uni_freiburg.es.sensorrecordingtool.sensors.LocationSensor.flush(LocationSensor.java:130)
03-25 08:50:02.728 12850-12850/es.uni_freiburg.de.cmotion W/System.err:     at de.uni_freiburg.es.sensorrecordingtool.sensors.SensorProcess.terminate(SensorProcess.java:190)
03-25 08:50:02.729 12850-12850/es.uni_freiburg.de.cmotion W/System.err:     at de.uni_freiburg.es.sensorrecordingtool.Recorder.onDestroy(Recorder.java:435)

**Comment by paulgavrikov** [comment]
Fixed by removing flush
